import './globals.css'
import { Header } from '@/components';
import SessionProvider from "../components/SessionProvider";
import { getServerSession } from 'next-auth';

export const metadata = {
  title: ' X-Rain Inc. Inventory Tracker',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className='relative flex flex-col min-h-screen'>
        <SessionProvider session={session} >
          <Header />
          {children}
        </SessionProvider>
      </body>
    </html>

  )
}
