import './globals.css'
import { Header } from '@/components';

export const metadata = {
  title: ' X-Rain Inc. Inventory Tracker',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
        <html lang="en">
        <body className='relative flex flex-col min-h-screen'>
            <Header />
            {children}
        </body>
    </html>

  )
}
